### ISSUE TITLE
Extra Arguments

### ISSUE THREAD

**Issue by ejferreira** [meetfinch/decking#88]
In the documentation it says:

extra        → extra runtime arguments, used as-is after the 'image' argument

However, it seems these arguments are being passed as a command for the container.
So, if I build the containers by my own, and use decking to start the clusters, the arguments are passed in runtime only (when the containers are launched), but if I try to build with decking build, the containers will have as the command, the extra arguments defined.
I think this is not the correct behavior.

**Comment by makeusabrew** [comment]
That's correct, and also expected. If you're creating the containers yourself then all decking will do (since they already exist) is effectively run `decking start` n times, once for each container in a cluster.

`decking start` takes no runtime parameters: https://docs.docker.com/reference/commandline/cli/#start

Only `decking create` takes arbitrary args: https://docs.docker.com/reference/commandline/cli/#create

So the only time we can pass `extra` args is at creation.

**Comment by ejferreira** [comment]
Yes that's true. I mean: docker create [OPTIONS] IMAGE [COMMAND] [ARG...]

Extra args are working for "[COMMAND] [ARG...]", so how can I set "[OPTIONS]" information?
I was tough "extra arguments" were related with theses options.
In my case I need to use arguments such as "host" that could not be defined in decking (json/yaml) properties file.

**Comment by ejferreira** [comment]
I find out a way to use what I need. Actually it seems like "host" property works in decking.yaml/json configuration?
Also in the image property I can pass [OPTIONS], that is correct?
I think you can close the issue.

Thank you.
